name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari jam 00:00 UTC
  workflow_dispatch: # bisa dijalankan manual
  push:
    branches: [ "main" ]

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint & format
        run: |
          npm run lint --if-present || true
          npm run format --if-present || true

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "chore: auto commit (lint/format/package-lock update)" || echo "No changes to commit"
          git push
