name: Auto Update Dependencies

on:
  schedule:
    - cron: "0 3 * * 1" # tiap Senin jam 03:00 UTC
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: |
          ncu -u
          npm install

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b chore/auto-deps-update
          git add package.json package-lock.json
          git commit -m "chore(deps): weekly auto update" || echo "No changes to commit"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/auto-deps-update
          base: main
          title: "chore(deps): weekly auto update"
          body: |
            This PR was created automatically by GitHub Actions.

            - Updated all dependencies to the latest stable versions.
            - Regenerated `package-lock.json`.

            Please review the changes before merging.
          labels: dependencies

      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-url != ''
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
