name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # bisa dijalankan manual

jobs:
  unit-tests:
    name: Run Unit Tests (Jest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install Dependencies
        run: npm install --no-fund --no-audit

      - name: Run Jest
        run: npm test -- --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jest-coverage
          path: coverage/

  e2e-tests:
    name: Run E2E Tests (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: |
            package-lock.json

      - name: Install Dependencies
        run: npm install --no-fund --no-audit

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
